import React, { useState, useEffect, useRef } from 'react';
import { A4SheetConfig, A4DensityOption } from '../types/avatar';
import { DICEBEAR_STYLES, getRandomSeed } from '../data/avatarApis';
import { 
  getResilientAvatarUrls, 
  loadImageWithAutoRepair,
  generateLocalSvgAvatar
} from '../utils/avatarFallback';
import { AutoHealAvatar } from './AutoHealAvatar';
import { TraitEditor } from './TraitEditor';
import { 
  AntiClogColorStrip, 
  CMYK_CHANNELS, 
  GRADIENT_FACTORS, 
  getStepRgb 
} from './AntiClogColorStrip';
import { generateUniqueExportFilename } from '../utils/filename';
import { 
  Download, 
  Printer, 
  Dices, 
  Sparkles, 
  FileImage, 
  ZoomIn, 
  ZoomOut,
  Palette,
  ShieldCheck,
  RefreshCw,
  Check
} from 'lucide-react';

const DENSITY_OPTIONS: A4DensityOption[] = [
  { cols: 4, rows: 6, total: 24, name: '4 × 6 (24 个大头像)', tagline: '画报大图，细节极其清晰' },
  { cols: 5, rows: 7, total: 35, name: '5 × 7 (35 个中头像)', tagline: '推荐经典比例，视觉平衡最佳' },
  { cols: 6, rows: 8, total: 48, name: '6 × 8 (48 个标准头像)', tagline: '贴纸集 / 花名册标准排版' },
  { cols: 7, rows: 10, total: 70, name: '7 × 10 (70 个密集头像)', tagline: '密集平铺，视觉冲击力强' },
  { cols: 8, rows: 12, total: 96, name: '8 × 12 (96 个微缩头像)', tagline: '海量图鉴，极致平铺' },
];

const SOFT_BG_COLORS = ['b6e3f4', 'c0aede', 'd1d4f9', 'ffd5dc', 'ffdfba', 'baffc9'];

const PRESET_BORDER_COLORS = [
  { name: '纯黑', hex: '#000000' },
  { name: '深灰石墨', hex: '#334155' },
  { name: '浅灰柔和', hex: '#94a3b8' },
  { name: '银白极淡', hex: '#cbd5e1' },
  { name: '经典靛蓝', hex: '#4f46e5' },
  { name: '珊瑚粉红', hex: '#e11d48' },
  { name: '薄荷清新', hex: '#059669' },
  { name: '暖阳金黄', hex: '#d97706' },
];

interface TileItem {
  id: string;
  style: string;
  seed: string;
  bgColor: string;
  candidates: string[];
}

// Convert HEX color + opacity (0-100) to rgba string
const hexToRgba = (hex: string, opacity: number): string => {
  let clean = (hex || '#000000').replace('#', '');
  if (clean.length === 3) {
    clean = clean.split('').map(c => c + c).join('');
  }
  const r = parseInt(clean.substring(0, 2), 16) || 0;
  const g = parseInt(clean.substring(2, 4), 16) || 0;
  const b = parseInt(clean.substring(4, 6), 16) || 0;
  const alpha = Math.max(0, Math.min(100, opacity)) / 100;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

export const A4SheetExporter: React.FC = () => {
  const [config, setConfig] = useState<A4SheetConfig>({
    styleMode: 'single',
    selectedStyle: 'adventurer',
    selectedStyles: ['adventurer', 'lorelei', 'avataaars', 'bottts', 'pixel-art', 'fun-emoji'],
    cols: 5,
    rows: 7,
    avatarShape: 'circle',
    hasBorder: true,
    borderColor: '#94a3b8',
    borderOpacity: 30,
    borderWidth: 1,
    borderLineStyle: 'solid',
    showLabels: true,
    sheetTitle: 'AVATAR COLLECTION',
    subtitle: 'A4 Printable Avatar Sheet · Generated by AvatarHub',
    avatarBgColor: 'transparent',
    traits: {
      enabled: false,
      gender: 'any',
      hairLength: 'any',
      hairColor: 'any',
      skinTone: 'any',
      mood: 'any',
      glasses: 'any',
      beard: 'any',
    },
    enableAntiClogStrip: true,
    antiClogShowHatch: true,
  });

  const [tiles, setTiles] = useState<TileItem[]>([]);
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);
  const [healedCount, setHealedCount] = useState(0);
  const [zoomLevel, setZoomLevel] = useState<number>(100);
  const [styleFilter, setStyleFilter] = useState<string>('all');
  const [styleSearch, setStyleSearch] = useState<string>('');
  const printContainerRef = useRef<HTMLDivElement>(null);

  const totalCount = config.cols * config.rows;

  const filteredStyles = DICEBEAR_STYLES.filter(s => {
    const matchCategory = styleFilter === 'all' || s.category === styleFilter;
    const matchSearch = !styleSearch.trim() || 
      s.name.toLowerCase().includes(styleSearch.toLowerCase()) || 
      s.nameZh.includes(styleSearch) ||
      s.id.includes(styleSearch.toLowerCase());
    return matchCategory && matchSearch;
  });

  // Re-generate tiles whenever density, styles, or seed changes
  const regenerateTiles = () => {
    const newTiles: TileItem[] = [];
    setHealedCount(0);
    
    for (let i = 0; i < totalCount; i++) {
      let chosenStyle = config.selectedStyle;
      if (config.styleMode === 'mixed') {
        const pool = config.selectedStyles.length > 0 ? config.selectedStyles : ['adventurer'];
        chosenStyle = pool[Math.floor(Math.random() * pool.length)];
      }

      const seed = getRandomSeed();
      const randomBg = config.avatarBgColor === 'random' 
        ? SOFT_BG_COLORS[Math.floor(Math.random() * SOFT_BG_COLORS.length)]
        : config.avatarBgColor !== 'transparent' ? config.avatarBgColor : '';

      const candidates = getResilientAvatarUrls(chosenStyle, seed, randomBg, config.traits);

      newTiles.push({
        id: `tile_${i}_${seed}`,
        style: chosenStyle,
        seed: seed,
        bgColor: randomBg,
        candidates: candidates
      });
    }
    setTiles(newTiles);
  };

  useEffect(() => {
    regenerateTiles();
  }, [config.cols, config.rows, config.selectedStyle, config.styleMode, config.selectedStyles, config.avatarBgColor, config.traits]);

  // Export as high-resolution PNG on white A4 canvas with automatic repair guarantee
  const handleExportA4Png = async () => {
    if (isExporting) return;
    setIsExporting(true);
    setExportProgress(5);

    try {
      // High-res A4 dimensions (1754 x 2480 at 150 DPI)
      const canvas = document.createElement('canvas');
      const width = 1754;
      const height = 2480;
      canvas.width = width;
      canvas.height = height;

      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Cannot get canvas context');

      // 1. Draw pristine pure white A4 background
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, width, height);

      // Margins
      const marginX = 80;
      let topY = 60;

      // Draw CMYK Anti-Clog Color Strip if enabled (matching reference photo: 10 seamless gradient steps, no percentages)
      if (config.enableAntiClogStrip) {
        const stripStartY = topY;
        const rowHeight = 32;
        const rowGap = 10;
        const labelWidth = 110;
        const barsStartX = marginX + labelWidth;
        const totalBarWidth = width - marginX * 2 - labelWidth;
        const blockWidth = totalBarWidth / GRADIENT_FACTORS.length;

        CMYK_CHANNELS.forEach((ch, idx) => {
          const currentY = stripStartY + idx * (rowHeight + rowGap);

          // 1. Channel Label: 黑 K, 青 C, 品红 M, 黄 Y (bold sans-serif, matching reference image)
          ctx.fillStyle = '#000000';
          ctx.font = 'bold 26px sans-serif';
          ctx.textAlign = 'left';
          ctx.fillText(ch.label, marginX + 4, currentY + 25);

          // 2. 10-step gradient blocks without percentage numbers
          GRADIENT_FACTORS.forEach((factor, fIdx) => {
            const bx = barsStartX + fIdx * blockWidth;
            ctx.fillStyle = getStepRgb(ch.r, ch.g, ch.b, factor);
            ctx.fillRect(bx, currentY, Math.ceil(blockWidth), rowHeight);
          });
        });

        topY += CMYK_CHANNELS.length * (rowHeight + rowGap) + 24;
      }

      // 2. Draw optional header
      if (config.sheetTitle) {
        ctx.fillStyle = '#0F172A';
        ctx.font = 'bold 44px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(config.sheetTitle, width / 2, topY + 40);

        if (config.subtitle) {
          ctx.fillStyle = '#64748B';
          ctx.font = '22px sans-serif';
          ctx.fillText(config.subtitle, width / 2, topY + 80);
        }

        // Hairline separator
        ctx.strokeStyle = '#E2E8F0';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(marginX, topY + 110);
        ctx.lineTo(width - marginX, topY + 110);
        ctx.stroke();

        topY += 140;
      }

      const availableHeight = height - topY - 80;
      const availableWidth = width - marginX * 2;

      const cellWidth = availableWidth / config.cols;
      const cellHeight = availableHeight / config.rows;
      const avatarSize = Math.min(cellWidth * 0.72, cellHeight * 0.72);

      // 3. Preload all images using Auto-Repair retry logic
      const total = tiles.length;
      let loadedCount = 0;

      for (let r = 0; r < config.rows; r++) {
        for (let c = 0; c < config.cols; c++) {
          const index = r * config.cols + c;
          if (index >= tiles.length) break;

          const tile = tiles[index];
          const cellCenterX = marginX + c * cellWidth + cellWidth / 2;
          const cellCenterY = topY + r * cellHeight + (config.showLabels ? cellHeight * 0.45 : cellHeight / 2);

          try {
            // Self-healing image loader: tries candidate URLs, never fails!
            const img = await loadImageWithAutoRepair(tile.candidates, 3000);

            ctx.save();

            // Handle shape clipping
            if (config.avatarShape === 'circle') {
              ctx.beginPath();
              ctx.arc(cellCenterX, cellCenterY, avatarSize / 2, 0, Math.PI * 2);
              ctx.clip();
            } else if (config.avatarShape === 'rounded') {
              const radius = avatarSize * 0.18;
              const x = cellCenterX - avatarSize / 2;
              const y = cellCenterY - avatarSize / 2;
              ctx.beginPath();
              ctx.moveTo(x + radius, y);
              ctx.lineTo(x + avatarSize - radius, y);
              ctx.quadraticCurveTo(x + avatarSize, y, x + avatarSize, y + radius);
              ctx.lineTo(x + avatarSize, y + avatarSize - radius);
              ctx.quadraticCurveTo(x + avatarSize, y + avatarSize, x + avatarSize - radius, y + avatarSize);
              ctx.lineTo(x + radius, y + avatarSize);
              ctx.quadraticCurveTo(x, y + avatarSize, x, y + avatarSize - radius);
              ctx.lineTo(x, y + radius);
              ctx.quadraticCurveTo(x, y, x + radius, y);
              ctx.closePath();
              ctx.clip();
            }

            // Draw avatar image
            ctx.drawImage(
              img,
              cellCenterX - avatarSize / 2,
              cellCenterY - avatarSize / 2,
              avatarSize,
              avatarSize
            );

            ctx.restore();

            // 4. Draw customizable border if enabled
            if (config.hasBorder) {
              ctx.save();
              ctx.strokeStyle = hexToRgba(config.borderColor, config.borderOpacity);
              ctx.lineWidth = Math.max(1, Math.round(config.borderWidth * 2.2));

              if (config.borderLineStyle === 'dashed') {
                ctx.setLineDash([8, 8]);
              } else if (config.borderLineStyle === 'dotted') {
                ctx.setLineDash([4, 6]);
              } else {
                ctx.setLineDash([]);
              }

              if (config.avatarShape === 'circle') {
                ctx.beginPath();
                ctx.arc(cellCenterX, cellCenterY, avatarSize / 2 + 2, 0, Math.PI * 2);
                ctx.stroke();
              } else if (config.avatarShape === 'rounded') {
                const radius = avatarSize * 0.18;
                const x = cellCenterX - avatarSize / 2 - 2;
                const y = cellCenterY - avatarSize / 2 - 2;
                const w = avatarSize + 4;
                const h = avatarSize + 4;
                ctx.beginPath();
                if (ctx.roundRect) {
                  ctx.roundRect(x, y, w, h, radius);
                } else {
                  ctx.strokeRect(x, y, w, h);
                }
                ctx.stroke();
              } else {
                // Square
                const x = cellCenterX - avatarSize / 2 - 2;
                const y = cellCenterY - avatarSize / 2 - 2;
                const w = avatarSize + 4;
                const h = avatarSize + 4;
                ctx.strokeRect(x, y, w, h);
              }
              ctx.restore();
            }

            // Draw label if enabled
            if (config.showLabels) {
              ctx.fillStyle = '#475569';
              ctx.font = '16px monospace';
              ctx.textAlign = 'center';
              const labelText = tile.seed.split('_')[0];
              ctx.fillText(labelText, cellCenterX, cellCenterY + avatarSize / 2 + 22);
            }
          } catch (e) {
            console.error('Self-healing canvas render note:', e);
          }

          loadedCount++;
          setExportProgress(Math.round(10 + (loadedCount / total) * 85));
        }
      }

      // 5. Download file with guaranteed unique filename (never repeats)
      canvas.toBlob((blob) => {
        if (!blob) throw new Error('Blob creation failed');
        const downloadUrl = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = downloadUrl;
        const styleName = config.styleMode === 'single' ? config.selectedStyle : 'mixed';
        a.download = generateUniqueExportFilename({
          prefix: 'A4_Avatar_Sheet',
          style: styleName,
          count: totalCount,
          ext: 'png'
        });
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(downloadUrl);
        setExportProgress(100);
        setTimeout(() => setIsExporting(false), 500);
      }, 'image/png', 0.95);

    } catch (err) {
      console.error('Export failed:', err);
      setIsExporting(false);
      alert('导出图片时遇到问题，已启动备用通道。');
    }
  };

  const handlePrint = () => {
    // Dynamically set document.title so browser's "Save as PDF" suggests a unique non-repeating filename
    const styleName = config.styleMode === 'single' ? config.selectedStyle : 'mixed';
    const uniquePdfTitle = generateUniqueExportFilename({
      prefix: 'A4_Avatar_Sheet',
      style: styleName,
      count: totalCount,
      ext: 'pdf'
    }).replace(/\.pdf$/i, '');

    const prevTitle = document.title;
    document.title = uniquePdfTitle;
    window.print();
    // Restore title after print dialog closes
    setTimeout(() => {
      document.title = prevTitle;
    }, 1500);
  };

  const borderCssRgba = config.hasBorder 
    ? hexToRgba(config.borderColor, config.borderOpacity) 
    : 'transparent';

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4 no-print">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-xs font-semibold text-indigo-600">
            <Sparkles className="w-3.5 h-3.5" />
            <span>A4 纯白背景平铺画报 / 头像贴纸排版器</span>
          </div>
          <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900">
            A4 随机头像平铺图纸生成与导出
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 max-w-2xl leading-relaxed">
            内置<strong>全自动防异常容灾引擎</strong>：若某头像因网络抖动或远端 CDN 限流导致加载失败，系统会自动无缝重试、回退至极速矢量引擎或离线自愈算法，<strong>100% 杜绝破图、白块或加载失败</strong>。
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2 shrink-0">
          <button
            onClick={regenerateTiles}
            className="flex items-center gap-2 px-3.5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs sm:text-sm font-semibold transition-all border border-slate-300 active:scale-95"
            title="全部重新随机摇号"
          >
            <Dices className="w-4 h-4 text-indigo-600 animate-spin-hover" />
            <span>🎲 重新随机生成</span>
          </button>

          <button
            onClick={handleExportA4Png}
            disabled={isExporting}
            className="flex items-center gap-2 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs sm:text-sm font-semibold shadow-md shadow-indigo-600/20 transition-all active:scale-95 disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>{isExporting ? `正在合成 ${exportProgress}%` : '导出 A4 白色背景图片 (PNG)'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs sm:text-sm font-semibold transition-all active:scale-95"
            title="调用浏览器原生高精度打印 / 另存为 A4 PDF"
          >
            <Printer className="w-4 h-4" />
            <span>打印 / 存为 PDF</span>
          </button>
        </div>
      </div>

      {/* Auto-Heal Status Notice */}
      <div className="rounded-xl bg-emerald-50/80 border border-emerald-200/80 px-4 py-3 flex items-center justify-between gap-3 text-xs text-emerald-950 no-print">
        <div className="flex items-center gap-2.5">
          <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>
            <strong>智能容灾与自动修复已激活：</strong> 优先使用高可用 SVG 纯矢量流；如遇外部服务超时，自动分级回退至通用图层或离线几何引擎，保障 A4 画布 100% 完整绘制。
          </span>
        </div>
        {healedCount > 0 && (
          <span className="font-mono text-emerald-700 font-bold bg-white px-2 py-0.5 rounded border border-emerald-200 shrink-0">
            已自动自愈 {healedCount} 个异常头像
          </span>
        )}
      </div>

      {/* Epson L4266 & Inkjet Anti-Clog Guard Active Notice */}
      {config.enableAntiClogStrip && (
        <div className="rounded-xl bg-indigo-50/80 border border-indigo-200/80 px-4 py-3 flex items-center justify-between gap-3 text-xs text-indigo-950 no-print animate-in fade-in">
          <div className="flex items-center gap-2.5">
            <span className="w-2.5 h-2.5 rounded-full bg-indigo-600 animate-pulse shrink-0" />
            <span>
              <strong>爱普生 L4266 喷墨防堵与 CMYK 状态校准色条已开启：</strong> A4 顶部将同步置入黑、青、品红、黄四色条（含 100% 实色、阶梯浅色与渐变过渡及喷嘴微型排查标尺），在每次打印时全通道出墨防干涸，并方便直观核对是否缺色或有白色拉丝横纹。
            </span>
          </div>
          <button
            onClick={() => setConfig(prev => ({ ...prev, enableAntiClogStrip: false }))}
            className="text-xs font-semibold text-indigo-700 hover:text-indigo-900 underline shrink-0"
          >
            关闭色条
          </button>
        </div>
      )}

      {/* Main Grid: Control Sidebar + A4 Sheet Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left: Configuration Controls (4 cols) */}
        <div className="lg:col-span-4 space-y-5 no-print">
          {/* 1. Style Selection */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <label className="text-xs font-bold uppercase tracking-wider text-slate-500">
                  1. 选择头像画风 (共 {DICEBEAR_STYLES.length} 款)
                </label>
                <span className="text-[10px] font-mono text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100">
                  显示 {filteredStyles.length} 款
                </span>
              </div>

              <div className="flex items-center gap-1 p-0.5 rounded-lg bg-slate-100 text-[11px] self-start sm:self-auto">
                <button
                  onClick={() => setConfig(prev => ({ ...prev, styleMode: 'single' }))}
                  className={`px-2.5 py-0.5 rounded-md font-medium transition-colors ${
                    config.styleMode === 'single' ? 'bg-white text-indigo-600 shadow-xs font-bold' : 'text-slate-500'
                  }`}
                >
                  单一风格
                </button>
                <button
                  onClick={() => setConfig(prev => ({ ...prev, styleMode: 'mixed' }))}
                  className={`px-2.5 py-0.5 rounded-md font-medium transition-colors ${
                    config.styleMode === 'mixed' ? 'bg-white text-indigo-600 shadow-xs font-bold' : 'text-slate-500'
                  }`}
                >
                  多风格混合
                </button>
              </div>
            </div>

            {/* Search Box */}
            <div className="relative">
              <input
                type="text"
                value={styleSearch}
                onChange={e => setStyleSearch(e.target.value)}
                placeholder="🔍 搜索风格 (如: 像素, 水彩, 机器人, Notion)..."
                className="w-full px-3 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-xl text-slate-900 focus:outline-none focus:border-indigo-500 placeholder-slate-400"
              />
              {styleSearch && (
                <button
                  onClick={() => setStyleSearch('')}
                  className="absolute right-3 top-2 text-xs text-slate-400 hover:text-slate-600"
                >
                  ×
                </button>
              )}
            </div>

            {/* Category tabs */}
            <div className="flex items-center gap-1 p-0.5 rounded-lg bg-slate-100 overflow-x-auto max-w-full">
              {[
                { id: 'all', label: '全部' },
                { id: 'cartoon', label: '🎨 卡通立绘' },
                { id: 'pixel', label: '👾 像素' },
                { id: 'robot', label: '🤖 机器人' },
                { id: 'minimal', label: '📝 Notion' },
                { id: 'fun', label: '🤪 搞怪' },
                { id: 'abstract', label: '🔷 抽象' },
              ].map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setStyleFilter(tab.id)}
                  className={`px-2 py-0.5 text-[11px] font-medium rounded-md whitespace-nowrap transition-colors ${
                    styleFilter === tab.id
                      ? 'bg-white text-indigo-600 shadow-xs font-semibold'
                      : 'text-slate-600 hover:text-slate-900'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {config.styleMode === 'single' ? (
              <div className="space-y-2">
                <span className="text-xs text-slate-500">点击指定平铺画风：</span>
                <div className="grid grid-cols-2 gap-2 max-h-60 overflow-y-auto pr-1">
                  {filteredStyles.map(style => {
                    const isSelected = config.selectedStyle === style.id;
                    return (
                      <button
                        key={style.id}
                        onClick={() => setConfig(prev => ({ ...prev, selectedStyle: style.id }))}
                        className={`flex items-center gap-2 p-2 rounded-xl border text-left transition-all ${
                          isSelected
                            ? 'bg-indigo-50 border-indigo-500 text-indigo-950 font-bold shadow-xs'
                            : 'bg-slate-50 border-slate-200 hover:border-slate-300 text-slate-700'
                        }`}
                      >
                        <AutoHealAvatar
                          styleName={style.id}
                          seed="Preview"
                          size={28}
                          className="w-7 h-7 rounded-lg bg-white border border-slate-200 shrink-0 object-cover"
                        />
                        <div className="min-w-0 flex-1">
                          <div className="text-xs truncate">{style.nameZh}</div>
                          <div className="text-[10px] font-mono text-slate-400 truncate">{style.id}</div>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-slate-500">勾选平铺画风池 (已选 {config.selectedStyles.length} 款)：</span>
                  <div className="flex items-center gap-1.5 text-[11px]">
                    <button
                      onClick={() => setConfig(prev => ({ ...prev, selectedStyles: DICEBEAR_STYLES.map(s => s.id) }))}
                      className="text-indigo-600 hover:underline"
                    >
                      全选30款
                    </button>
                    <span className="text-slate-300">|</span>
                    <button
                      onClick={() => setConfig(prev => ({ ...prev, selectedStyles: DICEBEAR_STYLES.filter(s => s.category === 'cartoon').map(s => s.id) }))}
                      className="text-indigo-600 hover:underline"
                    >
                      仅卡通
                    </button>
                    <span className="text-slate-300">|</span>
                    <button
                      onClick={() => setConfig(prev => ({ ...prev, selectedStyles: ['adventurer'] }))}
                      className="text-slate-400 hover:text-slate-600"
                    >
                      重置
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-2 max-h-60 overflow-y-auto pr-1">
                  {filteredStyles.map(style => {
                    const isChecked = config.selectedStyles.includes(style.id);
                    return (
                      <button
                        key={style.id}
                        onClick={() => {
                          setConfig(prev => {
                            const next = isChecked
                              ? prev.selectedStyles.filter(s => s !== style.id)
                              : [...prev.selectedStyles, style.id];
                            return { ...prev, selectedStyles: next.length > 0 ? next : ['adventurer'] };
                          });
                        }}
                        className={`flex items-center justify-between p-2 rounded-xl border text-left transition-all ${
                          isChecked
                            ? 'bg-indigo-50 border-indigo-500 text-indigo-950 font-bold'
                            : 'bg-slate-50 border-slate-200 text-slate-600'
                        }`}
                      >
                        <div className="min-w-0 flex-1">
                          <div className="text-xs truncate">{style.nameZh}</div>
                          <div className="text-[10px] font-mono text-slate-400 truncate">{style.id}</div>
                        </div>
                        {isChecked && <Check className="w-3.5 h-3.5 text-indigo-600 shrink-0 ml-1" />}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          {/* 2. Custom Traits & Factors (Gender, Hair, Skin, Mood) */}
          <TraitEditor
            traits={config.traits || {
              enabled: false,
              gender: 'any',
              hairLength: 'any',
              hairColor: 'any',
              skinTone: 'any',
              mood: 'any',
              glasses: 'any',
              beard: 'any',
            }}
            onChange={(newTraits) => setConfig(prev => ({ ...prev, traits: newTraits }))}
          />

          {/* 3. Density & Grid Layout */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
            <label className="text-xs font-bold uppercase tracking-wider text-slate-500">
              3. A4 排版密度与平铺总数
            </label>

            <div className="space-y-2">
              {DENSITY_OPTIONS.map(opt => {
                const isActive = config.cols === opt.cols && config.rows === opt.rows;
                return (
                  <button
                    key={`${opt.cols}x${opt.rows}`}
                    onClick={() => setConfig(prev => ({ ...prev, cols: opt.cols, rows: opt.rows }))}
                    className={`w-full flex items-center justify-between p-2.5 rounded-xl border text-left transition-all ${
                      isActive
                        ? 'bg-indigo-50 border-indigo-500 shadow-xs'
                        : 'bg-slate-50 border-slate-200 hover:border-slate-300'
                    }`}
                  >
                    <div>
                      <div className="text-xs font-bold text-slate-900">{opt.name}</div>
                      <div className="text-[11px] text-slate-500">{opt.tagline}</div>
                    </div>
                    {isActive && (
                      <span className="px-2 py-0.5 rounded-md bg-indigo-600 text-white text-[11px] font-semibold">
                        当前
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* 4. Detailed Border Customizer */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5">
                <Palette className="w-3.5 h-3.5 text-indigo-600" />
                <label className="text-xs font-bold uppercase tracking-wider text-slate-500">
                  4. 头像边框、颜色与透明度
                </label>
              </div>

              {/* Master Border Toggle */}
              <button
                onClick={() => setConfig(prev => ({ ...prev, hasBorder: !prev.hasBorder }))}
                className={`px-3 py-1 text-xs font-semibold rounded-lg border transition-all ${
                  config.hasBorder
                    ? 'bg-indigo-600 border-indigo-600 text-white shadow-xs'
                    : 'bg-slate-100 border-slate-200 text-slate-600'
                }`}
              >
                {config.hasBorder ? '边框已开启' : '无边框'}
              </button>
            </div>

            {config.hasBorder ? (
              <div className="space-y-4 pt-1 border-t border-slate-100 animate-in fade-in duration-150">
                {/* Border Color */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-600">边框颜色</span>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-slate-500 text-[11px] uppercase">{config.borderColor}</span>
                      <input
                        type="color"
                        value={config.borderColor}
                        onChange={e => setConfig(prev => ({ ...prev, borderColor: e.target.value }))}
                        className="w-5 h-5 rounded cursor-pointer border border-slate-300 p-0"
                        title="自定义拾色器"
                      />
                    </div>
                  </div>

                  {/* Preset Colors Grid */}
                  <div className="grid grid-cols-4 gap-1.5">
                    {PRESET_BORDER_COLORS.map(c => {
                      const isSelected = config.borderColor.toLowerCase() === c.hex.toLowerCase();
                      return (
                        <button
                          key={c.hex}
                          onClick={() => setConfig(prev => ({ ...prev, borderColor: c.hex }))}
                          className={`flex items-center gap-1.5 p-1.5 rounded-lg border text-left text-[11px] transition-all ${
                            isSelected 
                              ? 'border-indigo-600 bg-indigo-50 font-semibold text-indigo-950' 
                              : 'border-slate-200 bg-slate-50 hover:bg-white text-slate-700'
                          }`}
                        >
                          <span
                            className="w-3.5 h-3.5 rounded-full border border-slate-300 shrink-0"
                            style={{ backgroundColor: c.hex }}
                          />
                          <span className="truncate">{c.name}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Border Opacity Slider */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-600">边框透明度</span>
                    <span className="font-mono font-bold text-indigo-600">{config.borderOpacity}%</span>
                  </div>

                  <input
                    type="range"
                    min="5"
                    max="100"
                    step="5"
                    value={config.borderOpacity}
                    onChange={e => setConfig(prev => ({ ...prev, borderOpacity: Number(e.target.value) }))}
                    className="w-full accent-indigo-600"
                  />

                  {/* Quick opacity buttons */}
                  <div className="flex items-center gap-1.5 pt-0.5">
                    {[
                      { val: 100, label: '100% 纯色' },
                      { val: 60, label: '60%' },
                      { val: 30, label: '30% 默认' },
                      { val: 15, label: '15% 极浅' },
                    ].map(op => (
                      <button
                        key={op.val}
                        onClick={() => setConfig(prev => ({ ...prev, borderOpacity: op.val }))}
                        className={`flex-1 py-1 text-[11px] rounded-md border text-center transition-colors ${
                          config.borderOpacity === op.val
                            ? 'bg-indigo-600 border-indigo-600 text-white font-medium'
                            : 'bg-slate-50 border-slate-200 text-slate-600 hover:bg-white'
                        }`}
                      >
                        {op.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Line width and style */}
                <div className="grid grid-cols-2 gap-3 pt-1">
                  <div className="space-y-1.5">
                    <span className="text-xs text-slate-600">线宽</span>
                    <div className="grid grid-cols-4 gap-1 p-0.5 bg-slate-100 rounded-lg">
                      {[1, 2, 3, 4].map(w => (
                        <button
                          key={w}
                          onClick={() => setConfig(prev => ({ ...prev, borderWidth: w }))}
                          className={`py-1 text-xs font-mono rounded transition-colors ${
                            config.borderWidth === w
                              ? 'bg-white text-indigo-600 shadow-2xs font-bold'
                              : 'text-slate-600 hover:text-slate-900'
                          }`}
                        >
                          {w}px
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <span className="text-xs text-slate-600">线型</span>
                    <div className="grid grid-cols-3 gap-1 p-0.5 bg-slate-100 rounded-lg">
                      {[
                        { id: 'solid', label: '实线' },
                        { id: 'dashed', label: '虚线' },
                        { id: 'dotted', label: '点状' },
                      ].map(st => (
                        <button
                          key={st.id}
                          onClick={() => setConfig(prev => ({ ...prev, borderLineStyle: st.id as any }))}
                          className={`py-1 text-[11px] rounded transition-colors ${
                            config.borderLineStyle === st.id
                              ? 'bg-white text-indigo-600 shadow-2xs font-semibold'
                              : 'text-slate-600 hover:text-slate-900'
                          }`}
                        >
                          {st.label}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <p className="text-xs text-slate-400 py-1">
                已关闭边框。头像将纯净无外圈直接平铺在白色背景纸上。
              </p>
            )}
          </div>

          {/* 5. Shape & Sheet Title */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
            <label className="text-xs font-bold uppercase tracking-wider text-slate-500">
              5. 头像形状与标题设置
            </label>

            {/* Shape */}
            <div className="space-y-1.5">
              <span className="text-xs text-slate-600">头像形状</span>
              <div className="grid grid-cols-3 gap-1.5 p-1 bg-slate-100 rounded-xl">
                {[
                  { id: 'circle', label: '全圆 (贴纸)' },
                  { id: 'rounded', label: '圆角矩形' },
                  { id: 'square', label: '方形直角' }
                ].map(sh => (
                  <button
                    key={sh.id}
                    onClick={() => setConfig(prev => ({ ...prev, avatarShape: sh.id as any }))}
                    className={`py-1 text-xs font-medium rounded-lg transition-colors ${
                      config.avatarShape === sh.id
                        ? 'bg-white text-indigo-600 shadow-xs font-semibold'
                        : 'text-slate-600 hover:text-slate-900'
                    }`}
                  >
                    {sh.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Show labels toggle */}
            <div className="flex items-center justify-between pt-1 border-t border-slate-100">
              <span className="text-xs text-slate-700">显示头像下方 Seed 编号</span>
              <button
                onClick={() => setConfig(prev => ({ ...prev, showLabels: !prev.showLabels }))}
                className={`px-3 py-1 text-xs font-semibold rounded-lg border transition-colors ${
                  config.showLabels
                    ? 'bg-indigo-600 border-indigo-600 text-white'
                    : 'bg-slate-100 border-slate-200 text-slate-600'
                }`}
              >
                {config.showLabels ? '开启' : '关闭'}
              </button>
            </div>

            {/* Title */}
            <div className="space-y-1.5 pt-1 border-t border-slate-100">
              <span className="text-xs text-slate-700">A4 顶部标题 (留空则无标题纯头像)</span>
              <input
                type="text"
                value={config.sheetTitle}
                onChange={e => setConfig(prev => ({ ...prev, sheetTitle: e.target.value }))}
                placeholder="留空则无标题，纯头像铺满"
                className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl text-slate-900 focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          {/* 6. 爱普生喷墨防堵与 CMYK 检测色条 (Epson L4266 Guard) */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5">
                <Printer className="w-4 h-4 text-indigo-600" />
                <label className="text-xs font-bold uppercase tracking-wider text-slate-800">
                  6. 爱普生喷墨防堵与 CMYK 色条
                </label>
              </div>

              {/* Master Toggle */}
              <button
                onClick={() => setConfig(prev => ({ ...prev, enableAntiClogStrip: !prev.enableAntiClogStrip }))}
                className={`px-3 py-1 text-xs font-semibold rounded-lg border transition-all ${
                  config.enableAntiClogStrip
                    ? 'bg-emerald-600 border-emerald-600 text-white shadow-xs'
                    : 'bg-slate-100 border-slate-200 text-slate-600'
                }`}
              >
                {config.enableAntiClogStrip ? '已开启防堵色条' : '未开启'}
              </button>
            </div>

            {config.enableAntiClogStrip ? (
              <div className="space-y-3 pt-2 border-t border-slate-100 animate-in fade-in duration-150">
                <p className="text-[11px] text-slate-600 leading-relaxed">
                  在 A4 纸张顶部加入<strong>黑 (K)、青 (C)、品红 (M)、黄 (Y)</strong> 四条标准校准色带（包含 10 阶实色到浅色渐变方块，无文字干扰），方便肉眼对比观察是否缺色或有断线横纹。
                </p>

                {/* Mini Preview matching reference photo */}
                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                  <div className="space-y-1.5">
                    {CMYK_CHANNELS.map(ch => (
                      <div key={ch.label} className="flex items-center gap-2">
                        <span className="w-12 text-[11px] font-bold text-slate-800 shrink-0 font-sans">
                          {ch.label}
                        </span>
                        <div className="flex-1 grid grid-cols-10 h-4 rounded-xs overflow-hidden border border-slate-200">
                          {GRADIENT_FACTORS.map((factor, fIdx) => (
                            <div 
                              key={fIdx}
                              className="w-full h-full"
                              style={{
                                backgroundColor: getStepRgb(ch.r, ch.g, ch.b, factor)
                              }}
                            />
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Diagnostic helper guide */}
                <div className="rounded-xl bg-amber-50/80 border border-amber-200 p-3 text-[11px] text-amber-950 space-y-1.5 leading-relaxed">
                  <div className="font-bold flex items-center gap-1.5 text-amber-900">
                    <span>💡 爱普生 L4266 喷头观察指南：</span>
                  </div>
                  <ul className="list-disc pl-4 space-y-1 text-slate-700">
                    <li><strong>横纹断线排查</strong>：打印后若右侧浅色色块出现<strong>白色横向条纹或拉丝</strong>，说明对应颜色微压电喷嘴轻微堵塞或偏针；</li>
                    <li><strong>缺色判定</strong>：若左侧深色实色块未喷出或发白，说明对应墨路气阻或主喷嘴断墨；</li>
                    <li><strong>防堵养护</strong>：建议每周打印一次带四色彩带的画报，保持爱普生 L4266 墨路润滑畅通。</li>
                  </ul>
                </div>
              </div>
            ) : (
              <p className="text-[11px] text-slate-500">
                开启后将在 A4 顶部自动生成 CMYK 防堵色条，打印时让全部喷嘴均得到墨水湿润冲刷。
              </p>
            )}
          </div>
        </div>

        {/* Right: Realistic A4 Paper Sheet Preview (8 cols) */}
        <div className="lg:col-span-8 space-y-4">
          {/* Zoom & View toolbar */}
          <div className="flex items-center justify-between px-2 text-xs text-slate-500 no-print">
            <div className="flex items-center gap-2">
              <FileImage className="w-4 h-4 text-indigo-600" />
              <span className="font-semibold text-slate-800">
                A4 比例预览 (210mm × 297mm · 纯白底色)
              </span>
              <span>· 共 {totalCount} 个随机头像</span>
              {config.enableAntiClogStrip && (
                <span className="inline-flex items-center gap-1 text-[11px] text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200 font-medium">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                  <span>四色校准条已挂载</span>
                </span>
              )}
              {config.hasBorder && (
                <span className="inline-flex items-center gap-1 text-[11px] text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded-md border border-indigo-200">
                  <span
                    className="w-2.5 h-2.5 rounded-full inline-block border border-slate-300"
                    style={{ backgroundColor: borderCssRgba }}
                  />
                  <span>边框 {config.borderWidth}px · 透明度 {config.borderOpacity}%</span>
                </span>
              )}
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => setZoomLevel(prev => Math.max(70, prev - 15))}
                className="p-1.5 rounded-lg bg-white border border-slate-200 text-slate-600 hover:text-slate-900 shadow-2xs"
                title="缩小预览"
              >
                <ZoomOut className="w-3.5 h-3.5" />
              </button>
              <span className="font-mono text-[11px] text-slate-600 min-w-10 text-center">{zoomLevel}%</span>
              <button
                onClick={() => setZoomLevel(prev => Math.min(130, prev + 15))}
                className="p-1.5 rounded-lg bg-white border border-slate-200 text-slate-600 hover:text-slate-900 shadow-2xs"
                title="放大预览"
              >
                <ZoomIn className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>

          {/* Paper Canvas Container */}
          <div className="flex justify-center overflow-x-auto p-4 sm:p-8 bg-slate-200/70 rounded-3xl border border-slate-300/80 shadow-inner">
            <div
              id="a4-print-target"
              ref={printContainerRef}
              style={{
                width: `${680 * (zoomLevel / 100)}px`,
                minHeight: `${680 * 1.4142 * (zoomLevel / 100)}px`,
                backgroundColor: '#FFFFFF',
              }}
              className="relative p-6 sm:p-10 shadow-2xl transition-all duration-200 flex flex-col justify-between"
            >
              {/* Optional Anti-Clog CMYK Strip at the top of A4 paper */}
              {config.enableAntiClogStrip && (
                <AntiClogColorStrip />
              )}

              {/* Optional Header */}
              {config.sheetTitle && (
                <div className="text-center pb-4 mb-4 border-b border-slate-200">
                  <h2 className="text-base sm:text-xl font-extrabold tracking-wider text-slate-900 font-sans">
                    {config.sheetTitle}
                  </h2>
                  {config.subtitle && (
                    <p className="text-[11px] sm:text-xs text-slate-500 mt-0.5 font-sans">
                      {config.subtitle}
                    </p>
                  )}
                </div>
              )}

              {/* Tiled Avatars Grid with Auto-Healing */}
              <div
                className="flex-1 grid gap-2 sm:gap-3 items-center justify-items-center"
                style={{
                  gridTemplateColumns: `repeat(${config.cols}, minmax(0, 1fr))`,
                  gridTemplateRows: `repeat(${config.rows}, minmax(0, 1fr))`,
                }}
              >
                {tiles.map((tile) => (
                  <div
                    key={tile.id}
                    className="flex flex-col items-center justify-center w-full h-full text-center"
                  >
                    {/* Avatar Container with customizable border */}
                    <div
                      className="relative p-1 transition-all"
                      style={{
                        borderRadius: config.avatarShape === 'circle' ? '9999px' : config.avatarShape === 'rounded' ? '12px' : '0px',
                        border: config.hasBorder 
                          ? `${config.borderWidth}px ${config.borderLineStyle} ${borderCssRgba}`
                          : 'none',
                      }}
                    >
                      <AutoHealAvatar
                        styleName={tile.style}
                        seed={tile.seed}
                        bgColor={tile.bgColor}
                        traits={config.traits}
                        alt={tile.seed}
                        imgStyle={{
                          borderRadius: config.avatarShape === 'circle' ? '9999px' : config.avatarShape === 'rounded' ? '10px' : '0px',
                        }}
                        className="w-10 h-10 sm:w-14 sm:h-14 object-contain transition-transform hover:scale-110"
                        onHealed={() => setHealedCount(prev => prev + 1)}
                      />
                    </div>

                    {config.showLabels && (
                      <span className="text-[9px] sm:text-[10px] font-mono text-slate-500 truncate max-w-full mt-1">
                        {tile.seed.split('_')[0]}
                      </span>
                    )}
                  </div>
                ))}
              </div>

              {/* Sheet Footer Note */}
              <div className="pt-4 mt-4 border-t border-slate-100 flex items-center justify-between text-[9px] sm:text-[10px] text-slate-400 font-mono">
                <span>FORMAT: A4 PORTRAIT (210×297mm) · WHITE BACKGROUND</span>
                <span>TOTAL: {totalCount} AVATARS · ZERO BROKEN IMAGES</span>
              </div>
            </div>
          </div>

          {/* Printable tip banner */}
          <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-4 flex items-start gap-3 text-xs text-indigo-950 no-print">
            <Sparkles className="w-4 h-4 text-indigo-600 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <strong className="font-semibold text-indigo-900">智能修复与下载提示：</strong>
              <p className="text-slate-600 leading-relaxed text-[11px]">
                系统已内置<strong>毫秒级自动重试与多级容灾</strong>，即使用户处于弱网环境，导出的 A4 纯白背景图片也将 100% 完整生成，绝不出现残缺卡片或空白格子。
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
